name: Checksum

on:
  push:
    branches: [ "master" ]
    paths:
      - 'EasyListHebrew.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Validate Checksum
        id: checksum_validation
        run: |
          output=$(python3 .github/scripts/validateChecksum.py EasyListHebrew.txt)
          echo "Validation output is: $output"
          if [[ $output == "Checksum is valid" ]]; then
            echo "build=no" >> $GITHUB_ENV
            exit 0
          else
            echo 'Invalid checksum, creating a new one.'
            echo "build=yes" >> $GITHUB_ENV
          fi

      - name: Run the script
        if: env.build == 'yes'
        run: |
          tmpList=$(mktemp)
          python3 .github/scripts/addChecksum.py EasyListHebrew.txt $tmpList
          output=$(python3 .github/scripts/validateChecksum.py $tmpList)
          echo "Validation output for new file: $output"
          if [[ $output == "Checksum is valid" ]]; then
            mv -f $tmpList EasyListHebrew.txt
          else
            echo 'Something went wrong with checksum validation for the updated file.'
            exit 1
          fi
          python3 .github/scripts/genhosts.py EasyListHebrew.txt

      - name: Ensure EasyListHebrew.txt exists
        if: env.build == 'yes'
        run: |
          if [ ! -f EasyListHebrew.txt ]; then
            echo "Creating EasyListHebrew.txt"
            touch EasyListHebrew.txt
          fi

      - name: Update EasyListHebrew.txt file
        if: env.build == 'yes'
        run: |
            git config user.name "actions-user"
            git config user.email "actions@github.com"
            git add EasyListHebrew.txt
            git commit -m "Update Checksum"
            git push
