name: Checksum

on:
  push:
    branches: [ "master" ]
    paths:
      - 'EasyListHebrew.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Validate existing checksum
        id: validate_existing_checksum
        run: python .github/scripts/validateChecksum.py EasyListHebrew.txt

      - name: Run checksum update
        if: ${{ steps.validate_existing_checksum.conclusion == 'failure' }}
        id: update_checksum
        run: |
          tmpList=$(mktemp)
          python3 .github/scripts/addChecksum.py EasyListHebrew.txt $tmpList
          python3 .github/scripts/validateChecksum.py $tmpList
          if [ $? -ne 0 ]; then
            echo "Checksum validation failed after update"
            exit 1
          fi
          mv -f $tmpList EasyListHebrew.txt

      - name: Run genhosts
        id: genhosts
        run: python3 .github/scripts/genhosts.py EasyListHebrew.txt

      - name: Update EasyListHebrew.txt file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Checksum

      - name: Create Issue From File
        if: ${{ failure() }}
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Checksum failed please fix ASAP
          assignees: EasyListHebrew, Hebrew-uBO-User
          body: |
            The checksum validation and update process failed in the GitHub Action workflow.
            Please review `EasyListHebrew.txt` and ensure the checksum is correct.
            [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
